name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
        # Если есть requirements.txt, раскомментируйте следующую строку:
        # pip install -r requirements.txt

    - name: Run Black formatter check
      run: black --check --diff src/ tests/

    - name: Run flake8
      run: flake8 src/ tests/

    - name: Run tests
      run: pytest tests/