name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run linters
        run: |
          black --check src/ tests/
          isort --check src/ tests/
          flake8 src/ tests/

      - name: Add src to PYTHONPATH
        run: echo "$GITHUB_WORKSPACE/src" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/
