name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install black==23.7.0 isort==5.12.0 flake8==6.0.0 mypy==1.4.1 pytest==7.4.0 pytest-cov==4.1.0

      - name: Run code quality tools
        run: |
          echo "=== Running Black ==="
          black --check --diff .
          
          echo "=== Running isort ==="
          python -m isort --check-only --profile black src/ tests/
          
          echo "=== Running flake8 ==="
          flake8 src/ tests/
          
          echo "=== Running mypy ==="
          mypy src/ tests/

      - name: Run tests with coverage
        run: |
          echo "=== Running pytest with coverage ==="
          pytest tests/ -v --cov=src/ --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml