name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 pytest
          # или если у вас есть requirements.txt:
          # pip install -r requirements.txt

      - name: Run Black formatter
        run: |
          black src/ tests/
          git diff --exit-codeп

      - name: Run flake8
        run: flake8 src/ tests/

      - name: Run pytest
        run: pytest tests/