name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install black==23.7.0 isort==5.12.0 flake8==6.0.0 mypy==1.4.1 pytest==7.4.0

      - name: Auto-format with Black
        run: |
          black .
          git diff --exit-code || (echo "1" && exit 1)

      - name: Run isort
        run: python -m isort --check-only --profile black src/ tests/

      - name: Run flake8
        run: flake8 src/ tests/

      - name: Run mypy
        run: mypy src/ tests/

      - name: Run pytest
        run: pytest tests/ -v