name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify Python version
        run: python --version

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest  # если нет requirements.txt

      - name: Run Black formatter
        run: black --check src/ tests/

      - name: Run isort
        run: isort --check --profile black src/ tests/

      - name: Run flake8
        run: flake8 src/ tests/

      - name: Run pytest
        run: pytest tests/